name: "Velbus serial to TCP interface"
description: "This addon will make a TCP server from a serial device, this allows hassio and velbuslink to work simultanious on the bus"
version: "0.1.0"
slug: "velbusd"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
ports:
  27015/tcp: 27015
options:
  auth:
    enabled: true
    synctime: "03:00"
  serial:
    autodiscover: true
    port: ""
  logging:
    type: "debug"
schema:
  auth:
    enabled: bool
    synctime: match(^[0-2][0-9]:[0-5][0-9]$)
  serial:
    autodiscover: bool
    port: ""
  logging:
    type: list(trace|debug|info|notice|warning|error|fatal)?  
  
