name: "Velbus serial to TCP interface"
description: "This addon will make a TCP server from a serial device, this allows hassio and velbuslink to work simultanious on the bus"
version: "0.1.0"
slug: "velbusd"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
watchdog: tcp://[HOST]:[PORT]
ports:
  27015/tcp: 27015
options:
  ntp: true
  serial: str
    autodiscover: true
    port: ""
  logging: "debug"
schema:
  ntp: bool
  serial:
    autodiscover: bool
    port: str
  logging: list(trace|debug|info|notice|warning|error|fatal)?  
  
