name: "Velbus serial to TCP interface"
description: "This addon will make a TCP server from a serial device, this allows hassio and velbuslink to work simultanious on the bus"
version: "0.1.21"
slug: "velbusd"
init: false
apparmor: false
url: https://github.com/cereal2nd/hassio-velbusd
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
watchdog: tcp://[HOST]:[PORT:27015]
ports:
  27015/tcp: 27015
ports_description:
  27015/tcp: The port that should be used for velbustcp
options:
  velbus: ""
  auth: false
  authkey: ""
  ntp: true
  logging: "debug"
schema:
  velbus: device(subsystem=tty)
  auth: bool
  authkey: str?
  ntp: bool
  logging: list(debug|info)
